### metrics
GET http://localhost:9080/debug/vars


### ProductList
GRPC localhost:8080/api.storage.v2.StorageService/ProductList


### ProductGet
GRPC localhost:8080/api.storage.v2.StorageService/ProductGet

{
  "id": 1
}


### ProductCreate
GRPC localhost:8080/api.storage.v2.StorageService/ProductCreate

{
  "name": "NewProduct2",
  "price": 3,
  "quantity": 100
}


### ProductUpdate
GRPC localhost:8080/api.storage.v2.StorageService/ProductUpdate

{
  "id": "1",
  "name": "newPillow",
  "price": "300",
  "quantity": "20"
}


### ProductDelete
GRPC localhost:8080/api.storage.v2.StorageService/ProductDelete

{
  "id": 1
}
