### metrics
GET http://localhost:9081/debug/vars


### ProductList
GRPC localhost:8081/api.v1.ApiService/ProductList

#{
#  "page": 1,
#  "size": 3
#}


### ProductGet
GRPC localhost:8081/api.v1.ApiService/ProductGet

{
  "id": 133
}


### ProductCreate
GRPC localhost:8081/api.v1.ApiService/ProductCreate

{
  "name": "product 5",
  "price": 30,
  "quantity": 100
}


### ProductUpdate
GRPC localhost:8081/api.v1.ApiService/ProductUpdate

{
  "id": 133,
  "name": "product 2 updated",
  "price": 300,
  "quantity": 200
}


### ProductDelete
GRPC localhost:8081/api.v1.ApiService/ProductDelete

{
  "id": 138
}
