
### ProductList
GRPC localhost:8080/api.v1.AdminService/ProductList


### ProductGet
GRPC localhost:8080/api.v1.AdminService/ProductGet

{
  "id": 1
}


### ProductCreate
GRPC localhost:8080/api.v1.AdminService/ProductCreate

{
  "name": "NewProduct2",
  "price": 3,
  "quantity": 100
}


### ProductUpdate
GRPC localhost:8080/api.v1.AdminService/ProductUpdate

{
  "id": "1",
  "name": "newPillow",
  "price": "300",
  "quantity": "20"
}


### ProductDelete
GRPC localhost:8080/api.v1.AdminService/ProductDelete

{
  "id": 2
}
